---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/docuum --version
    register: docuum_test_output
  - name: docuum --version
    debug:
      msg: '{{ docuum_test_output.stdout }}'
