---
- hosts: all
  vars:
    docker_engine_manage_service: false
    docuum_config:
      enable: false
      activate: false
  roles:
  - andrewrothstein.docker_engine
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/docuum --version
    register: docuum_test_output
  - name: docuum --version
    debug:
      msg: '{{ docuum_test_output.stdout }}'
