---
- name: Create docuum service account
  ansible.builtin.include_role:
    name: andrewrothstein.service_account
  vars:
    service_account:
      user:
        name: '{{ docuum_config.user | default("docuum") }}'
        group: '{{ docuum_config.group | default("docuum") }}'
        append: true
        groups:
          - docker
