---
- name: Creating systemd service
  ansible.builtin.include_role:
    name: andrewrothstein.systemd_service
  vars:
    systemd_service_def:
      enabled: '{{ docuum_config.enabled }}'
      activate: '{{ docuum_config.activate }}'
      name: '{{ docuum_config.name | default("docuum") }}'
      account:
        enabled: '{{ docuum_config.enabled }}'
        user: '{{ docuum_config.user | default("docuum") }}'
        group: '{{ docuum_group }}'
        append: true
        groups: [docker]
      description: Docuum
      start:
        exe: /usr/local/bin/docuum
        args: --threshold $DOCUUM_THRESHOLD
      env:
        dir: /etc/docuum
        filename: env
        data:
          DOCUUM_THRESHOLD: '{{ docuum_config.threshold | default("100GB") }}'
      restart:
        policy: on-failure
      after:
        - docker.service
      wants:
        - docker.service
      wanted_by:
        - multi-user.target
